spring:
  application:
    name: server-registry
server:
  port: 19002
eureka:
  instance:
    hostname: server-registry2
    appname: server-registry
  client:
    service-url:
      defaultZone:  http://server-registry1:19001/eureka,http://server-registry3:19003/eureka