spring:
  application:
    name: server-registry
server:
  port: 19001
eureka:
  instance:
    hostname: server-registry1
    appname: server-registry
  client:
    service-url:
      defaultZone:  http://server-registry2:19001/eureka,http://server-registry3:19003/eureka
    register-with-eureka: true
    fetch-registry: false