spring:
  application:
    name: server-registry
server:
  port: 19003
eureka:
  instance:
    hostname: server-registry3
    appname: server-registry
  client:
    service-url:
      defaultZone:  http://server-registry1:19001/eureka,http://server-registry2:19002/eureka