#给自己本地使用
spring:
  application:
    name: server-registry
server:
  port: 19000
eureka:
#  server:
#    # 单机环境下关闭自我保护
#    enable-self-preservation: false
  instance:
    hostname: server-registry0
    appname: server-registry0
  client:
    service-url:
      defaultZone:  http://server-registry0:19000/eureka
    register-with-eureka: false
    fetch-registry: false